//! Workload generation for database performance and latency benchmarking.
//!
//! Provides a flexible YCSB-compliant workload generator supporting:
//! - Uniform, Zipfian, and Latest key access distributions
//! - Standard YCSB workload presets (Workload A through Workload F)
//! - Point lookups, updates, inserts, range scans, deletes, and read-modify-writes
//! - Deterministic, reproducible generation with seedable PRNG

use serde::{Deserialize, Serialize};
use serde_json::{Value, json};

/// Fast, seedable pseudo-random number generator (SplitMix64) with no external dependencies.
#[derive(Clone, Debug)]
pub struct FastRng {
    state: u64,
}

impl FastRng {
    /// Create a new PRNG with an initial 64-bit seed.
    pub fn new(seed: u64) -> Self {
        Self {
            state: if seed == 0 { 0x853c49e6748fea9b } else { seed },
        }
    }

    /// Generate the next pseudo-random `u64`.
    pub fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9e3779b97f4a7c15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d049bb133111eb);
        z ^ (z >> 31)
    }

    /// Generate a pseudo-random integer in `[0, max)`.
    pub fn next_range(&mut self, max: usize) -> usize {
        if max <= 1 {
            0
        } else {
            (self.next_u64() % (max as u64)) as usize
        }
    }

    /// Generate a pseudo-random `f64` in `[0.0, 1.0)`.
    pub fn next_f64(&mut self) -> f64 {
        let v = (self.next_u64() >> 11) as f64;
        v / ((1u64 << 53) as f64)
    }

    /// Generate a pseudo-random alphanumeric string of given byte length.
    pub fn random_string(&mut self, len: usize) -> String {
        const CHARSET: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
        let mut buf = Vec::with_capacity(len);
        for _ in 0..len {
            let idx = self.next_range(CHARSET.len());
            buf.push(CHARSET[idx]);
        }
        // Safety: CHARSET contains only ASCII bytes.
        String::from_utf8(buf).unwrap()
    }
}

/// Zipfian distribution generator using Gray/Cooper algorithm.
#[derive(Clone, Debug)]
pub struct ZipfianGenerator {
    items: usize,
    theta: f64,
    alpha: f64,
    zeta_n: f64,
    eta: f64,
    _zeta_2: f64,
}

impl ZipfianGenerator {
    /// Create a new Zipfian generator for `items` elements with skew parameter `theta`.
    pub fn new(items: usize, theta: f64) -> Self {
        let items = items.max(2);
        let zeta_2 = Self::zeta(2, theta);
        let zeta_n = Self::zeta(items, theta);
        let alpha = 1.0 / (1.0 - theta);
        let eta = (1.0 - (2.0 / items as f64).powf(1.0 - theta)) / (1.0 - zeta_2 / zeta_n);

        Self {
            items,
            theta,
            alpha,
            zeta_n,
            eta,
            _zeta_2: zeta_2,
        }
    }

    /// Compute generalized harmonic number $\zeta(n, \theta)$.
    fn zeta(n: usize, theta: f64) -> f64 {
        let mut sum = 0.0;
        for i in 1..=n {
            sum += 1.0 / (i as f64).powf(theta);
        }
        sum
    }

    /// Draw a sample index in `0..items`.
    pub fn sample(&self, rng: &mut FastRng) -> usize {
        let u = rng.next_f64().clamp(1e-10, 1.0 - 1e-10);
        let uz = u * self.zeta_n;

        if uz < 1.0 {
            return 0;
        }
        if uz < 1.0 + 0.5f64.powf(self.theta) {
            return 1;
        }

        let k = (self.items as f64 * (self.eta * u - self.eta + 1.0).powf(self.alpha)) as usize;
        k.min(self.items - 1)
    }

    /// Update item count dynamically when records are added.
    pub fn update_item_count(&mut self, new_items: usize) {
        if new_items > self.items {
            *self = Self::new(new_items, self.theta);
        }
    }
}

/// Key access distribution strategy.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub enum Distribution {
    /// Uniformly distributed across all active keys.
    Uniform,
    /// Power-law Zipfian distribution (hot-spot skew).
    Zipfian { theta: f64 },
    /// Biased towards the most recently inserted keys.
    Latest,
}

/// Operations generated by the workload runner.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum WorkloadOperation {
    /// Point lookup by key.
    Read { key: String },
    /// Update existing key with new value.
    Update { key: String, value: Value },
    /// Insert a new unique record.
    Insert { key: String, value: Value },
    /// Sequential prefix scan with max record limit.
    Scan { prefix: String, limit: usize },
    /// Delete a record.
    Delete { key: String },
    /// Read, modify a numeric field, and write back.
    ReadModifyWrite {
        key: String,
        field: String,
        delta: i64,
    },
}

/// Standard YCSB workload presets.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorkloadPreset {
    /// Workload A: Update heavy (50% Read, 50% Update, Zipfian).
    YcsbA,
    /// Workload B: Read heavy (95% Read, 5% Update, Zipfian).
    YcsbB,
    /// Workload C: Read only (100% Read, Zipfian).
    YcsbC,
    /// Workload D: Read latest (95% Read Latest, 5% Insert).
    YcsbD,
    /// Workload E: Short range scan (95% Scan, 5% Insert, Uniform).
    YcsbE,
    /// Workload F: Read-modify-write (50% Read, 50% RMW, Zipfian).
    YcsbF,
    /// Point lookup benchmark (100% Read, Uniform).
    PointLookup,
    /// Write heavy benchmark (10% Read, 90% Insert/Update, Uniform).
    WriteHeavy,
}

/// Configuration for workload generation.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WorkloadConfig {
    pub key_count: usize,
    pub value_size_bytes: usize,
    pub distribution: Distribution,
    pub read_ratio: f64,
    pub update_ratio: f64,
    pub insert_ratio: f64,
    pub scan_ratio: f64,
    pub rmw_ratio: f64,
    pub delete_ratio: f64,
    pub scan_max_limit: usize,
    pub collection: String,
    pub seed: u64,
}

impl Default for WorkloadConfig {
    fn default() -> Self {
        Self {
            key_count: 1000,
            value_size_bytes: 256,
            distribution: Distribution::Zipfian { theta: 0.99 },
            read_ratio: 0.50,
            update_ratio: 0.50,
            insert_ratio: 0.0,
            scan_ratio: 0.0,
            rmw_ratio: 0.0,
            delete_ratio: 0.0,
            scan_max_limit: 100,
            collection: "users".to_string(),
            seed: 42,
        }
    }
}

/// Stateful workload generator producing reproducible sequences of operations.
pub struct WorkloadGenerator {
    config: WorkloadConfig,
    rng: FastRng,
    zipfian: Option<ZipfianGenerator>,
    current_key_count: usize,
    cum_read: f64,
    cum_update: f64,
    cum_insert: f64,
    cum_scan: f64,
    cum_rmw: f64,
    _cum_delete: f64,
}

impl WorkloadGenerator {
    /// Create a generator from explicit config.
    pub fn new(config: WorkloadConfig) -> Self {
        let rng = FastRng::new(config.seed);
        let zipfian = match config.distribution {
            Distribution::Zipfian { theta } => Some(ZipfianGenerator::new(config.key_count, theta)),
            _ => None,
        };

        let total = config.read_ratio
            + config.update_ratio
            + config.insert_ratio
            + config.scan_ratio
            + config.rmw_ratio
            + config.delete_ratio;
        let total = if total <= 0.0 { 1.0 } else { total };

        let cum_read = config.read_ratio / total;
        let cum_update = cum_read + (config.update_ratio / total);
        let cum_insert = cum_update + (config.insert_ratio / total);
        let cum_scan = cum_insert + (config.scan_ratio / total);
        let cum_rmw = cum_scan + (config.rmw_ratio / total);
        let _cum_delete = 1.0;

        let current_key_count = config.key_count;

        Self {
            config,
            rng,
            zipfian,
            current_key_count,
            cum_read,
            cum_update,
            cum_insert,
            cum_scan,
            cum_rmw,
            _cum_delete,
        }
    }

    /// Create a generator from a standard preset.
    pub fn from_preset(preset: WorkloadPreset, key_count: usize, value_size_bytes: usize) -> Self {
        let mut config = WorkloadConfig {
            key_count,
            value_size_bytes,
            collection: "benchmarks".into(),
            seed: 0xDEADBEEF,
            ..Default::default()
        };

        match preset {
            WorkloadPreset::YcsbA => {
                config.distribution = Distribution::Zipfian { theta: 0.99 };
                config.read_ratio = 0.50;
                config.update_ratio = 0.50;
            }
            WorkloadPreset::YcsbB => {
                config.distribution = Distribution::Zipfian { theta: 0.99 };
                config.read_ratio = 0.95;
                config.update_ratio = 0.05;
            }
            WorkloadPreset::YcsbC => {
                config.distribution = Distribution::Zipfian { theta: 0.99 };
                config.read_ratio = 1.00;
                config.update_ratio = 0.00;
            }
            WorkloadPreset::YcsbD => {
                config.distribution = Distribution::Latest;
                config.read_ratio = 0.95;
                config.insert_ratio = 0.05;
            }
            WorkloadPreset::YcsbE => {
                config.distribution = Distribution::Uniform;
                config.scan_ratio = 0.95;
                config.insert_ratio = 0.05;
                config.scan_max_limit = 50;
            }
            WorkloadPreset::YcsbF => {
                config.distribution = Distribution::Zipfian { theta: 0.99 };
                config.read_ratio = 0.50;
                config.rmw_ratio = 0.50;
            }
            WorkloadPreset::PointLookup => {
                config.distribution = Distribution::Uniform;
                config.read_ratio = 1.00;
            }
            WorkloadPreset::WriteHeavy => {
                config.distribution = Distribution::Uniform;
                config.read_ratio = 0.10;
                config.update_ratio = 0.45;
                config.insert_ratio = 0.45;
            }
        }

        Self::new(config)
    }

    /// Generate an initial dataset of records according to `key_count` and `value_size_bytes`.
    pub fn generate_initial_dataset(&mut self) -> Vec<(String, Value)> {
        let mut dataset = Vec::with_capacity(self.config.key_count);
        for i in 0..self.config.key_count {
            let key = self.key_for_index(i);
            let val = self.create_record_value(i, self.config.value_size_bytes);
            dataset.push((key, val));
        }
        dataset
    }

    /// Produce the next workload operation in the sequence.
    pub fn next_op(&mut self) -> WorkloadOperation {
        let roll = self.rng.next_f64();

        if roll < self.cum_read {
            let idx = self.sample_key_index();
            WorkloadOperation::Read {
                key: self.key_for_index(idx),
            }
        } else if roll < self.cum_update {
            let idx = self.sample_key_index();
            let value = self.create_record_value(idx, self.config.value_size_bytes);
            WorkloadOperation::Update {
                key: self.key_for_index(idx),
                value,
            }
        } else if roll < self.cum_insert {
            let idx = self.current_key_count;
            self.current_key_count += 1;
            if let Some(ref mut z) = self.zipfian {
                z.update_item_count(self.current_key_count);
            }
            let key = self.key_for_index(idx);
            let value = self.create_record_value(idx, self.config.value_size_bytes);
            WorkloadOperation::Insert { key, value }
        } else if roll < self.cum_scan {
            let idx = self.sample_key_index();
            let prefix = format!("{}/user_{:08}", self.config.collection, idx / 100);
            let limit = 1 + self.rng.next_range(self.config.scan_max_limit.max(1));
            WorkloadOperation::Scan { prefix, limit }
        } else if roll < self.cum_rmw {
            let idx = self.sample_key_index();
            WorkloadOperation::ReadModifyWrite {
                key: self.key_for_index(idx),
                field: "counter".into(),
                delta: 1,
            }
        } else {
            let idx = self.sample_key_index();
            WorkloadOperation::Delete {
                key: self.key_for_index(idx),
            }
        }
    }

    /// Formats key as `{collection}/user_{index:08}`.
    pub fn key_for_index(&self, index: usize) -> String {
        format!("{}/user_{:08}", self.config.collection, index)
    }

    /// Samples an index according to the configured distribution.
    pub fn sample_key_index(&mut self) -> usize {
        let max = self.current_key_count.max(1);
        match self.config.distribution {
            Distribution::Uniform => self.rng.next_range(max),
            Distribution::Zipfian { .. } => {
                if let Some(ref z) = self.zipfian {
                    z.sample(&mut self.rng).min(max - 1)
                } else {
                    self.rng.next_range(max)
                }
            }
            Distribution::Latest => {
                // Bias towards the upper 10% of keys
                if max > 10 && self.rng.next_f64() < 0.85 {
                    let start = max - (max / 10).max(1);
                    start + self.rng.next_range(max - start)
                } else {
                    self.rng.next_range(max)
                }
            }
        }
    }

    /// Creates a deterministic JSON record value of specified approximate byte length.
    pub fn create_record_value(&mut self, index: usize, size_bytes: usize) -> Value {
        let id_str = format!("user_{:08}", index);
        let padding_needed = size_bytes.saturating_sub(64);
        let payload = self.rng.random_string(padding_needed);

        json!({
            "id": id_str,
            "counter": index as i64,
            "active": true,
            "data": payload
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fast_rng_produces_deterministic_sequences() {
        let mut rng1 = FastRng::new(12345);
        let mut rng2 = FastRng::new(12345);
        for _ in 0..100 {
            assert_eq!(rng1.next_u64(), rng2.next_u64());
            assert_eq!(rng1.next_range(50), rng2.next_range(50));
            assert_eq!(rng1.next_f64(), rng2.next_f64());
        }
    }

    #[test]
    fn zipfian_distribution_favors_lower_ranks() {
        let items = 1000;
        let zipf = ZipfianGenerator::new(items, 0.99);
        let mut rng = FastRng::new(999);
        let mut counts = vec![0usize; items];
        let samples = 10_000;

        for _ in 0..samples {
            let idx = zipf.sample(&mut rng);
            assert!(idx < items);
            counts[idx] += 1;
        }

        // The top 10% of keys should capture over 40% of accesses with theta=0.99
        let top_10_percent = &counts[0..(items / 10)];
        let top_10_sum: usize = top_10_percent.iter().sum();
        assert!(
            top_10_sum > (samples * 40 / 100),
            "Top 10% received {}/{} samples",
            top_10_sum,
            samples
        );
    }

    #[test]
    fn generator_creates_initial_dataset_and_ycsb_presets() {
        for preset in [
            WorkloadPreset::YcsbA,
            WorkloadPreset::YcsbB,
            WorkloadPreset::YcsbC,
            WorkloadPreset::YcsbD,
            WorkloadPreset::YcsbE,
            WorkloadPreset::YcsbF,
            WorkloadPreset::PointLookup,
            WorkloadPreset::WriteHeavy,
        ] {
            let mut generator = WorkloadGenerator::from_preset(preset, 50, 128);
            let dataset = generator.generate_initial_dataset();
            assert_eq!(dataset.len(), 50);
            assert!(dataset[0].0.starts_with("benchmarks/user_"));

            for _ in 0..100 {
                let op = generator.next_op();
                match op {
                    WorkloadOperation::Read { ref key }
                    | WorkloadOperation::Update { ref key, .. }
                    | WorkloadOperation::Insert { ref key, .. }
                    | WorkloadOperation::Delete { ref key }
                    | WorkloadOperation::ReadModifyWrite { ref key, .. } => {
                        assert!(key.starts_with("benchmarks/user_"));
                    }
                    WorkloadOperation::Scan { ref prefix, limit } => {
                        assert!(prefix.starts_with("benchmarks/user_"));
                        assert!(limit > 0);
                    }
                }
            }
        }
    }
}
